# Generated by Django 2.0.4 on 2018-06-02 11:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180602_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='text'),
        ),
    ]
